"""feat: persist task execution parameters

Revision ID: 1f3f6e1e3fff
Revises: 5f86b03eb931
Create Date: 2026-08-30 12:52:42.880620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3f6e1e3fff'
down_revision: Union[str, Sequence[str], None] = '5f86b03eb931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('tasks', sa.Column('kb_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'kb_path')
    op.drop_column('tasks', 'file_path')
    # ### end Alembic commands ###
