"""add chunk status

Revision ID: c77fc836a1eb
Revises: 4d1494046dda
Create Date: 2026-09-11 15:25:21.544314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77fc836a1eb'
down_revision: Union[str, Sequence[str], None] = '4d1494046dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_chunk_status'), 'chunk', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_status'), table_name='chunk')
    op.drop_column('chunk', 'status')
    # ### end Alembic commands ###
