"""add document type

Revision ID: ea22f5674c06
Revises: 1f3f6e1e3fff
Create Date: 2026-09-01 21:27:38.686225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea22f5674c06'
down_revision: Union[str, Sequence[str], None] = '1f3f6e1e3fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('document_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'document_type')
    # ### end Alembic commands ###
